name: 'docs'

on: [ push, pull_request ]

env:
  # https://github.com/tox-dev/tox/issues/1468
  PY_COLORS: 1
  CLONE_VUNIT: git clone --recurse-submodules -j4 https://github.com/VUnit/vunit ../vunit

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        pip install -U pip --progress-bar off
        pip install -U virtualenv tox --progress-bar off
    - name: get VUnit
      run: $CLONE_VUNIT
    - name: build docs
      run: tox -e py38-docs -- --color
    - uses: actions/upload-artifact@master
      with:
        name: VUnit-site
        path: .tox/py38-docs/tmp/docsbuild/
    - name: 'publish site to gh-pages'
      if: github.event_name != 'pull_request' && github.repository == 'VUnit/cosim'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd .tox/py38-docs/tmp/docsbuild/
        touch .nojekyll

        git init
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -a -m "update ${{ github.sha }}"

        git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git push -u origin +HEAD:gh-pages
